### ISSUE TITLE
Have error creating 

### ISSUE THREAD

**Issue by bkacer** [stackTom/AutomaticWaterMasking#1]
Got this msg: Something went wrong while creating water mask polygons for tile +49+015. Either .....

Those 3 resample files have downloaded and placed in main EarthTiles dir. ScenProc downloaded and path set to my P3D dir + path fixed in FSEarthMasks.ini. 

Trying to generate map of city "Svetla nad Sazavou, Czech Republic"
49,40,16 N
15,24,00 E

Download resulution set to -1
Earth service: Google Earth
Mask: Yes
Comp. Scen.: Yes
Use Cash: Yes
Use Scenproc: Yes

on Win 10 Pro

For the first time I tried it was working, but then I close the running CMD window.  After that it won't work again and getting this msg. Tried delete all files and setup again, diff. Earth Service provider, diff. Download res., restart Win, but nothing works.

![Screenshot 2023-06-12 113520](https://github.com/stackTom/AutomaticWaterMasking/assets/78692976/6ca62e8f-38ee-4cc2-937d-ea5c158ee5fa)

**Comment by stackTom** [comment]
Please delete the C:\FSET\WORK\Tiles and C:\FSET\WORK\OSM_data folders. Close FSET, and try again. It's working fine on my computer, so I think some of your .osm files got corrupted.

**Comment by bkacer** [comment]
Didn't help, then I tried start completely again from start (delete all, unpack, set ini etc a still didn't work, the same msg: Download failed using https://overpass-api.de/api/map?bbox=... trying new overpass server in 32 seconds, and then the popup error window..

**Comment by stackTom** [comment]
Try visiting these links in a browser and tell me if they successfully download:
`http://overpass-api.de/api/interpreter?data=(way["natural"="coastline"](49, 15, 50, 16););(._;>>;);out body;`


`http://overpass-api.de/api/interpreter?data=(rel["natural"="water"](49, 15, 50, 16);rel["waterway"="riverbank"](49, 15, 50, 16);way["natural"="water"](49, 15, 50, 16);way["waterway"="riverbank"](49, 15, 50, 16);way["waterway"="dock"](49, 15, 50, 16););(._;>>;);out body;`

Those are the links the program uses to download the osm data.

**Comment by bkacer** [comment]
Have no problem with download..  2 files "interpreter", one 269 b, second 28.5 MB

**Comment by stackTom** [comment]
I am at a loss. Can you completely close FSET, then take a short video so I can see what's going on?

The problem seems to be that the software can't download the OSM data. Which is something I haven't run into before. It's especially weird since your browser downloads it fine. And your scenery is working fine on 3 computers I've tested.

**Comment by bkacer** [comment]
ok give me a minute.. :)

**Comment by bkacer** [comment]
https://tempclip.com/TbkJQGgsDVml78p/watch

**Comment by stackTom** [comment]
Are you able to create any scenery? What happens when you make scenery elsewhere in the world? Try somewhere else and let me know. I've never seen this bug before nor have any of the beta testers.

**Comment by stackTom** [comment]
Also, can you change your computer to English and region to USA as a test? FSET has weird issues sometimes when the format of dates, numbers, etc is from a different region.

**Comment by bkacer** [comment]
yeah, I tried different locations (usa, germany), but never worked. It only work for the very first time, after I download and setup everything. I let it run for about 1 min, just to see if it works, then I closed the running CMD window. After an hour, i tried again, and then it didn't work. I tried delete everything, start again completely from scratch, edit INI, even restart win..

**Comment by stackTom** [comment]
I'll have to send you a debug build so I can get more information on why failing. I have no idea currently. What a strange bug.

**Comment by stackTom** [comment]
> yeah, I tried different locations (usa, germany), but never worked. It only work for the very first time, after I download and setup everything. I let it run for about 1 min, just to see if it works, then I closed the running CMD window. After an hour, i tried again, and then it didn't work. I tried delete everything, start again completely from scratch, edit INI, even restart win.. 

Can you change your region/language on windows to USA/English? Please try that before I send you the debug build as I have a feeling that's where the problem is.

**Comment by bkacer** [comment]
wow, that's what it was.. It's working now..    thank's for help !  :)

**Comment by stackTom** [comment]
No problem. I'll try to fix that bug with different languages at some point.
